# Generated by Django 4.2.13 on 2024-05-12 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProctoringApp', '0002_rename_title_exam_subject_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10),
        ),
    ]
