# Generated by Django 4.2.13 on 2024-05-13 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProctoringApp', '0004_alter_exam_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('In Active', 'In Active'), ('Completed', 'Completed')], default='In Active', max_length=10),
        ),
    ]
